repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: "doc/keyseer.txt"
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/JohnnyMorganz/StyLua
  rev: v0.18.1
  hooks:
  - name: Run stylua
    id: stylua-github
- repo: local
  hooks:
      - id: check-documentation
        name: Ensure documentation has been updated
        language: system
        types: [lua]
        entry: make documentation-ci
